### ISSUE TITLE
Adding a pypi package?

### ISSUE THREAD

**Issue by knc6** [aspuru-guzik-group/tequila#130]
Currently, I am using a pip+git install in jarvis-tools (https://github.com/usnistgov/jarvis/blob/master/jarvis/io/tequila/inputs.py).
For CI/CD purposes, please consider to have a pypi package for tequila.

**Comment by kottmanj** [comment]
Working on it :-)

**Comment by kottmanj** [comment]
Should work now. Note that you can't do `pip install tequila` since that package already exists.
I have created  `pip install tequila-basic` (installs tequila with basic dependencies, i.e. without all the simulators; they can be installed before or after, independent of the tequila installation
