### ISSUE TITLE
Tagging package

### ISSUE THREAD

**Issue by mlxd** [aspuru-guzik-group/tequila#131]
Hi, we are currently using tequila as part of quantum chemistry circuit generation work. I am hoping it may be possible to periodically tag versions of the repository with a given set of changes. Right now we have a specific merge commit hash as the chosen version we use, but would prefer tags, eg `git checkout v0.1.0`, or similar.

Is this something that would be possible? Happy to discuss our use of this package over a call if that would help.

**Comment by kottmanj** [comment]
I have to admit, that I didn't had the best discipline with git tags until now. Wanted to wait until our overview article is out and start with v1.0.0. This is basically now, so I could finally do this. Thanks for the push.

Feel free to let us know if there are any other problems/inconveniences with the package.

**Comment by mlxd** [comment]
Great, thanks a lot --- this should help us quite a bit. We must say that is has been very useful having access to this package, so great work on everything. I will close this issue.
