### ISSUE TITLE
Bug Calculating the number of virtual orbitals in make_uccsd_ansatz

### ISSUE THREAD

**Issue by snow0369** [aspuru-guzik-group/tequila#165]
Hi.

In the code,
(https://github.com/aspuru-guzik-group/tequila/blob/master/src/tequila/quantumchemistry/qc_base.py#L1421), 

```python
nvirt = self.n_orbitals // 2 - nocc
```

I think here `self.n_orbital` is the number of spatial orbitals, not spin orbitals.
Therefore, `//2` gives a false value for `nvirt`.
Should it be like this?

```python
nvirt = self.n_orbitals - nocc
```

Thank you.

**Comment by kottmanj** [comment]
Yes, that is a bug.
Thanks for noticing! If you are interested in fixing it with a Pull Request (fix is exactly what you propose), let me know. Otherwise I'll fix it in the next days.

Fortunately it doesn't matter when guess amplitudes are used (also why it was not detected by the test suite).

**Comment by kottmanj** [comment]
Fixed. Thanks :-)
