### ISSUE TITLE
Support for multiple IBM providers

### ISSUE THREAD

**Issue by HermanniH** [aspuru-guzik-group/tequila#44]
I haven't found a way to execute my qt.simulate() call on IBM because my account has access to multiple providers. The open provider is for everyone, the others are for members of hubs.

In simulator_qiskit (and maybe elsewhere too) tequila does this:
backend = IBMQ.get_provider().get_backend(machine)

When the user has access to multiple providers (default + premium), you need to run this:
provider = IBMQ.get_provider(hub=‘your hub’, group=‘your group’, project=‘your project’)
backend = provider.get_backend(machine)

The same structure of the code works for anyone if you use:
IBMQ.get_provider(hub=‘ibm-q’, group=‘open’, project=‘main’)
backend = provider.get_backend(machine)

But then you access the public devices with public priority. There should be a way in tequila to input the provider as an option.

**Comment by kottmanj** [comment]
Hi Hermanni,
Thanks for the feedback!

You can specify the provider and/or backend yourself and pass this down the simulate or compile function.
Either as dictionary or as initialized imbq backend.

It should work like this (can't say for non public imbq accounts, I just tested with the fake/mock provider right now. Can you let me know if it worked?)

provider = qiskit.IBMQ.get_provider(hub=‘ibm-q’, group=‘open’, project=‘main’)
device = provider.get_backend("device_name") 
result = tq.simulate(objective, samples=100, backend="qiskit",  device = device)

or alternatively
result = tq.simulate(objective, samples=100, backend="qiskit", device = {"provider":provider, "name":device_name}

Can you let me know if that works for you?
Sorry, the tutorial is not so clear about that, will fix that!

Best wishes from Toronto

**Comment by HermanniH** [comment]
Thanks Jakob! 

Yeah I couldn't figure this out from the docs. I thought I had to input the name of the device only, but if I can input the actual device object then there is no problem. Now it works!

Thanks for your help!
