### ISSUE TITLE
Issues installing Tequila

### ISSUE THREAD

**Issue by mjrk9** [aspuru-guzik-group/tequila#78]
Hi, I'm having some issues following the windows installation guide. I've cloned the git link but when running setup.py (after editing requirements.txt) I run into the following error:

```
An exception has occurred, use %tb to see the full traceback.

SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized
```

The above is in Jupyter notebook and repeating the same process in a spyder document gives: 

```

An exception has occurred, use %tb to see the full traceback.

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

```
Do you have any idea what could be causing this? Thanks!

**Comment by kottmanj** [comment]
Hi,
It does not look like a tequila specific error. Can you provide us with a bit more information:
- Are you trying to install it directly from jupyter? 
- Can you send the commands you used to do it and which command produced this error? 

In general I would try to not install it from jupyter but directly through command line.

**Comment by mjrk9** [comment]
Hi,
I did try running directly from jupyter using 

`%run setup.py`

as well as copying all of steup.py into jupyter and running it. I just tried running setup through cmd too and it gave
```
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied 
```
I used some print statements and it seems the error arises from 
```
setup(
    name='tequila',
    version="1.0",
    author='Jakob S. Kottmann, Sumner Alperin-Lea, Teresa Tamayo-Mendoza, Cyrille Lavigne, Alba Cervera-Lierta, Abhinav Anand, Maha Kesebi, and others',
    author_email='jakob.kottmann@gmail.com',

    install_requires=requirements + additional,
    extras_require={
        ':python_version < "3.7"': extras_3_6,
        ':python_version == "3.7"': extras_3_7
    },

    packages=find_packages(where='src'),

    package_dir={'': 'src'},

    include_package_data=True,

    package_data={
        '': [os.path.join('src')]       
    }
)
```

**Comment by kottmanj** [comment]
Hi,

I'm having a bit trouble to understand where the error arises from. Just to be sure: You are installing from a jupyter notebook. Is this notebook in the same directory as the tequila source code (thats the directory where you cloned the code from which contains the folders 'src' and 'tutorials' etc and which has the files 'setup.py' and the modified 'requirements.txt'

Could you try installing from command line:

cd into the directory where you cloned tequila (the one where setup.py is)
activate your python environment (if you use one) 
then type 

pip install --upgrade -r requirements.txt
pip install -e .

(requirements.txt should be the modified file, and don't forget the "." in the end of the second command)

if no errors occur until that point, start python and try to import tequila

If this does not work: Can you post the error traceback here?

**Comment by mjrk9** [comment]
That seems to have worked! Thank you so much for the help.
