### ISSUE TITLE
Attribute error in BasicUsage tutorial

### ISSUE THREAD

**Issue by nonhermitian** [aspuru-guzik-group/tequila#81]
Installed latest master branch.

<img width="1171" alt="Screen Shot 2020-11-03 at 19 48 21" src="https://user-images.githubusercontent.com/1249193/98056287-8df53e80-1e0d-11eb-9438-60b276e4bb99.png">

**Comment by kottmanj** [comment]
Thank you for notifying! 
The tutorials are currently in the updating process.
Should be done by the end of the week.

Until then: Read out for sampled evaluation can now be specified externally (not tied to the circuit anymore).
In this example it would be:
tq.simulate(circuit, samples=10, read_out_qubits=[0])

As far as I can see it shouldn't affect the rest of the tutorial.

**Comment by kottmanj** [comment]
Thanks @nonhermitian  and @clausia :-)
